name = "territorial-signaling"
main = "signaling-worker.js"
compatibility_date = "2026-06-23"

[[durable_objects.bindings]]
name = "MATCHMAKER"
class_name = "Matchmaker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Matchmaker"]
